github.com:
    users:
        zaidwaqi:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zaidwaqi
